parser: babel-eslint

extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:react/recommended
  - standard
  - standard-react

env:
  node: true
  browser: true
  jest: true

rules:
  # stylistic
  comma-dangle: [2, always-multiline]
  eol-last: 2
  object-curly-spacing: [2, always]

  # eslint
  no-unused-vars: [2, { argsIgnorePattern: ^_, varsIgnorePattern: ^_ }]

  # es6
  object-shorthand: 2

  # react
  react/display-name: 0
  react/prop-types: [2, skipUndeclared: true]
  react/jsx-no-target-blank: [2, enforceDynamicLinks: never]
